---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  vars:
    servicio: tomcat
    puerto: 8080
  tasks:
    - name: Comprobar servicio
      ansible.builtin.service:
        name: "{{ servicio }}"    
        state: started
      register: status

    - name: Verificar servicio
      ansible.builtin.assert:
        that: not status.changed
        success_msg: "{{ servicio }} levantado y corriendo"
        fail_msg: "{{ servicio }} No estaba levantado"

    - name: Comprobar conexion a pagina
      ansible.builtin.uri:
        url: http://localhost:{{ puerto }}
      register: pagina

    - name: Comprobar codigo http
      ansible.builtin.assert:
        that: pagina.status == 200
        success_msg: "Conexion a pagina {{ servicio }} OK"
        fail_msg: "Error en conexion a pagina {{ servicio }}"

...
