---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Comprobar instalacion java
      ansible.builtin.command:
        cmd: java -version
      register: comando    


    - name: Verificar instalacion java
      ansible.builtin.assert:
        that: comando.rc == 0
        success_msg: "Java instalado"
        fail_msg: "Java NO instalado"
