---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  vars:
    servicio: tomcat
    puerto: 8080
  vars_files:
    - vault.yml
  tasks:
    - name: Comprobar conexion a pagina
      ansible.builtin.uri:
        url: http://localhost:{{ puerto }}/manager/status
        user: "{{ user }}"
        password: "{{ password }}"
      register: pagina

    - name: Comprobar codigo http
      ansible.builtin.assert:
        that: pagina.status == 200
        success_msg: "Conexion a pagina {{ servicio }} OK"
        fail_msg: "Error en conexion a pagina {{ servicio }}"
